// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayNode(r []Node, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeNode(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayNodeWrapper struct {
	Target *[]Node
}

func (_ ArrayNodeWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayNodeWrapper) Finalize()                        {}
func (_ ArrayNodeWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayNodeWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Node, 0, s)
	}
}
func (r ArrayNodeWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayNodeWrapper) AppendArray() types.Field {
	var v Node
	v = NewNode()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
