// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Kind int32

const (
	KindA Kind = 0
	KindB Kind = 1
	KindC Kind = 2
)

func (e Kind) String() string {
	switch e {
	case KindA:
		return "A"
	case KindB:
		return "B"
	case KindC:
		return "C"
	}
	return "unknown"
}

func writeKind(r Kind, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewKindValue(raw string) (r Kind, err error) {
	switch raw {
	case "A":
		return KindA, nil
	case "B":
		return KindB, nil
	case "C":
		return KindC, nil
	}

	return -1, fmt.Errorf("invalid value for Kind: '%s'", raw)

}

func (b Kind) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *Kind) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewKindValue(stringVal)
	*b = val
	return err
}

type KindWrapper struct {
	Target *Kind
}

func (b KindWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b KindWrapper) SetInt(v int32) {
	*(b.Target) = Kind(v)
}

func (b KindWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b KindWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b KindWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b KindWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b KindWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b KindWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b KindWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b KindWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b KindWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b KindWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b KindWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b KindWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b KindWrapper) Finalize() {}
