// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapFoo(r map[string]Foo, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeFoo(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapFooWrapper struct {
	Target *map[string]Foo
	keys   []string
	values []Foo
}

func (_ *MapFooWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapFooWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapFooWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapFooWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]Foo, 0, s)
	}
}

func (r *MapFooWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapFooWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapFooWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v Foo
	v = NewFoo()

	r.values = append(r.values, v)
	return &types.Record{Target: &r.values[len(r.values)-1]}
}

func (_ *MapFooWrapper) AppendArray() types.Field { panic("Unsupported operation") }
