// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     schema.avsc
 */
package avro

import (
	"encoding/json"
	"io"

	"github.com/actgardner/gogen-avro/v10/util"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeMD5(r MD5, w io.Writer) error {
	_, err := w.Write(r[:])
	return err
}

type MD5Wrapper struct {
	Target *MD5
}

type MD5 [16]byte

func (b *MD5) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	codepoints := util.DecodeByteString(s)
	copy((*b)[:], codepoints)
	return nil
}

func (b MD5) MarshalJSON() ([]byte, error) {
	return []byte(util.EncodeByteString(b[:])), nil
}

func (_ MD5Wrapper) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ MD5Wrapper) SetInt(v int32)      { panic("Unsupported operation") }
func (_ MD5Wrapper) SetLong(v int64)     { panic("Unsupported operation") }
func (_ MD5Wrapper) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ MD5Wrapper) SetDouble(v float64) { panic("Unsupported operation") }
func (r MD5Wrapper) SetBytes(v []byte) {
	copy((*r.Target)[:], v)
}
func (_ MD5Wrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ MD5Wrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ MD5Wrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ MD5Wrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ MD5Wrapper) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ MD5Wrapper) NullField(int)                    { panic("Unsupported operation") }
func (_ MD5Wrapper) HintSize(int)                     { panic("Unsupported operation") }
func (_ MD5Wrapper) Finalize()                        {}
func (_ MD5Wrapper) SetDefault(i int)                 { panic("Unsupported operation") }
